### PR TITLE
Add missing textdomain

### PR DESCRIPTION
**Pull request by hinaloe**
Some translate string not have plugin textdomain (like a120af01143f12183ce1fc16f824318ea76ef42a). This adds some one.

### CODE REVIEW

**Comment by maximebj** [comment]
Thanks, 
I found some and fixed some of them in 1.7
Some strings are from WordPress (like "Common") so it's normal than they don't have a textdomain.
Can you fix it please just this, and I'll accept the PR.

Thank you for your help!

**Comment by hinaloe** [comment]
No, WP Core Translation does not have `Common`, but `Common blocks` is exist. so, they are not translated. ([Translation Consistency](https://translate.wordpress.org/consistency/?search=Common&set=ja%2Fdefault&project=) is good way for know it)

Furthermore, other words translated in the core (eg embed) may not be appropriate for block headings in some languages.

**Comment by maximebj** [comment]
Translation may have changed since I've made this. So the fix needed is to set __( 'Common blocks' ) instead, is this right?

**Comment by hinaloe** [comment]
That's one of way.
However, the real solution is that you don't know when the words used in the WordPress core change, and you shouldn't rely on it.

> If there are strings in your plugin that are also used in WordPress core (e.g. ‘Settings’), you should still add your own text domain to them, otherwise they’ll become untranslated if the core string changes (which happens).
>
> -- https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#add-text-domain-to-strings

**Comment by maximebj** [comment]
Fair enough ! 
The doc is on your side ;) 
I'll merge your PR and search for other missing texdomain.

**Pull request merged**
